name: CI

on:
    push:
    pull_request:

jobs:
    run-tests:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                python-version:
                    - "3.10"
                    - "3.11"

        name: datamodels test
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set Python Up
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: python -m pip install -r requirements.txt
            
            - name: Test
              run: |
                python -m pytest tests
                ./shell/schema.sh
